/**
 * Cloudflare Pages Function: /api/send-email
 *
 * This file is automatically picked up by Cloudflare Pages as a serverless
 * function at the route /api/send-email. Environment variables (SMTP_USER,
 * SMTP_PASS, MAIL_TO, etc.) must be configured in the Cloudflare Pages
 * dashboard under Settings → Environment Variables for production.
 *
 * For local dev, Vite proxies /api → the Express server (server/index.ts).
 */

interface Env {
  SMTP_HOST?: string;
  SMTP_PORT?: string;
  SMTP_USER?: string;
  SMTP_PASS?: string;
  MAIL_TO?: string;
}

interface EmailPayload {
  name: string;
  email: string;
  phone?: string;
  message?: string;
  page?: string;
  fields?: Record<string, string>;
}

// Simple in-memory rate limiter (resets per isolate, good enough for edge)
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();

function checkRateLimit(ip: string): boolean {
  const now = Date.now();
  const windowMs = 15 * 60 * 1000; // 15 min
  const entry = rateLimitMap.get(ip);
  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + windowMs });
    return true;
  }
  if (entry.count >= 5) return false;
  entry.count++;
  return true;
}

function buildHtml(payload: EmailPayload, subject: string): string {
  const timestamp = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });

  let bodyRows = `
    <tr><td><b>Name</b></td><td>${payload.name}</td></tr>
    <tr><td><b>Email</b></td><td>${payload.email}</td></tr>
    <tr><td><b>Phone</b></td><td>${payload.phone || "—"}</td></tr>
  `;

  if (payload.fields) {
    Object.entries(payload.fields).forEach(([key, value]) => {
      bodyRows += `<tr><td><b>${key}</b></td><td>${value || "—"}</td></tr>`;
    });
  }

  if (payload.message) {
    bodyRows += `<tr><td><b>Message</b></td><td>${payload.message}</td></tr>`;
  }

  bodyRows += `
    <tr><td><b>Page</b></td><td>${payload.page || "Contact"}</td></tr>
    <tr><td><b>Timestamp</b></td><td>${timestamp}</td></tr>
  `;

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
      <div style="background: #003087; padding: 20px 24px;">
        <h2 style="color: white; margin: 0; font-size: 18px;">IEEE SOU SB — ${subject}</h2>
      </div>
      <div style="padding: 24px;">
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <tbody style="line-height: 2;">
            ${bodyRows}
          </tbody>
        </table>
      </div>
      <div style="background: #f3f4f6; padding: 12px 24px; font-size: 12px; color: #6b7280;">
        This email was automatically generated by the IEEE SOU SB website.
      </div>
    </div>
  `;
}

/**
 * Send email via MailChannels (Cloudflare native)
 */
async function sendViaMailChannels(
  from: string,
  to: string,
  replyTo: string,
  subject: string,
  html: string
): Promise<{ ok: boolean; status: number; body: string }> {
  const response = await fetch("https://api.mailchannels.net/tx/v1/send", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      personalizations: [
        {
          to: [{ email: to }],
          reply_to: { email: replyTo },
        },
      ],
      from: { email: from, name: "IEEE SOU SB Website" },
      subject,
      content: [{ type: "text/html", value: html }],
    }),
  });

  const body = await response.text().catch(() => "");
  return { ok: response.status === 202 || response.status === 200, status: response.status, body };
}

export const onRequestPost: PagesFunction<Env> = async (context) => {
  const { request, env } = context;

  // CORS headers
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };

  // OPTIONS preflight
  if (request.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  // Rate limiting
  const ip = request.headers.get("CF-Connecting-IP") || "unknown";
  if (!checkRateLimit(ip)) {
    return new Response(
      JSON.stringify({ error: "Too many requests, please try again later." }),
      { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  let payload: EmailPayload;
  try {
    payload = (await request.json()) as EmailPayload;
  } catch {
    return new Response(
      JSON.stringify({ error: "Invalid JSON body." }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  const { name, email, phone, message, page, fields } = payload;

  // Validation
  if (!name || !email) {
    return new Response(
      JSON.stringify({ error: "Name and email are required." }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  const mailTo = Object.keys(env).length > 0 && env.MAIL_TO ? env.MAIL_TO : "events.ieee@socet.edu.in";
  const smtpUser = Object.keys(env).length > 0 && env.SMTP_USER ? env.SMTP_USER : "events.ieee@socet.edu.in";

  const subject =
    page === "Join"
      ? "New Join Request — IEEE SOU SB"
      : "New Contact Form Submission — IEEE SOU SB";

  const html = buildHtml({ name, email, phone, message, page, fields }, subject);

  // Send via MailChannels 
  // We use the SMTP_USER as the 'from' address since Cloudflare recommends sending from a verified domain.
  const fromEmail = smtpUser || mailTo;
  
  const result = await sendViaMailChannels(fromEmail, mailTo, email, subject, html);

  if (result.ok) {
    return new Response(
      JSON.stringify({ success: true, message: "Email sent successfully." }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  console.error("MailChannels error:", result.status, result.body);
  return new Response(
    JSON.stringify({ error: "Failed to send email. Please ensure your Cloudflare configuration is correct. " + result.body }),
    { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
  );
};

// Handle OPTIONS for CORS preflight
export const onRequestOptions: PagesFunction = async () => {
  return new Response(null, {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
};
